ProjetFinalWeb/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using stream.api;
using System.Collections.Generic;

namespace ProjetFinalWeb.Models
{
	public class DefaultDbContext : DbContext
	{
		public DefaultDbContext(DbContextOptions options) : base(options)
		{

		}

		protected DefaultDbContext()
		{

		}

		/// <summary>
		/// C'est une LISTE ! et elle sera connectée à une table en bdd
		/// </summary>
		public DbSet<Viewer> Viewers { get; set; }
	}
}

ProjetFinalWeb/Models/ErrorViewModel.cs
namespace ProjetFinalWeb.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ProjetFinalWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetFinalWeb.Models;
using System.Diagnostics;

namespace ProjetFinalWeb.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ProjetFinalWeb/Controllers/ViewerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetFinalWeb.Models;
using stream.api;
using System.Collections.Generic;

namespace ProjetFinalWeb.Controllers
{
	public class ViewerController : Controller
	{
		private readonly DefaultDbContext context;

		public ViewerController(DefaultDbContext context)
		{
			this.context = context;
		}

		// GET: ViewerController
		public IActionResult List()
		{
			// Prepa requete linq => ça ne fait rien
			var query = from item in this.context.Viewers
						where item.actif.Equals(true)
						select item;

			var modelAEnvoyerALaView = query.ToList(); // Traduction, requete linq en requete sql
			var vueAAppeler = "List";
			return View(vueAAppeler, modelAEnvoyerALaView);
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		// Post: ViewerController/Listfilter
		[HttpPost]
		public ActionResult Listfilter()
		{
			int nbStreamStreamer = int.Parse(this.Request.Form["choix"]);
			var query = from item in this.context.Viewers
						where item.actif.Equals(true) && (item.nbStreamRegardes * 100 / nbStreamStreamer) >= 70
						select item;

			if (nbStreamStreamer == 0)
			{
				// Prepa requete linq => ça ne fait rien
				query = from item in this.context.Viewers
							where item.actif.Equals(true)
							select item;
			} else
			{
			}
			// Prepa requete linq => ça ne fait rien
			var modelAEnvoyerALaView = query.ToList(); // Traduction, requete linq en requete sql
			var vueAAppeler = "List";
			return View(vueAAppeler, modelAEnvoyerALaView);
		}

		// GET: ViewerController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: ViewerController/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: ViewerController/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ViewerController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: ViewerController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: ViewerController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: ViewerController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

ProjetFinalWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetFinalWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetFinalWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetFinalWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetFinalWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Viewer" asp-action="List">Liste des viewers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetFinalWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjetFinalWeb/Views/VIewer/List.cshtml
<form asp-action="Listfilter" asp-controller="Viewer" method="post">
	<select name="choix">
		<option value="0">Tous les viewers</option>
		<option value="10">Les plus présents</option>
	</select>
	<button type="submit">Filter</button>
</form>

<table class="table">
	<thead>
		<tr>
			<th>
				Id
			</th>
			<th>
				prenom
			</th>
			<th>
				email
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var viewer in Model)
		{
			<tr>
				<td>@viewer.id</td>
				<td>@viewer.prenom</td>
				<td>@viewer.email</td>
			</tr>
		}
	</tbody>
</table>