ProjetFinalWeb2/Models/DefaultDbContext.cs
using Microsoft.EntityFrameworkCore;
using stream.api;

namespace ProjetFinalWeb2.Models
{
	public class DefaultDbContext : DbContext
	{
		public DefaultDbContext(DbContextOptions options) : base(options)
		{

		}

		protected DefaultDbContext()
		{

		}

		/// <summary>
		/// C'est une LISTE ! et elle sera connectée à une table en bdd
		/// </summary>
		public DbSet<stream.api.Stream> Streams { get; set; }
	}
}

ProjetFinalWeb2/Models/ErrorViewModel.cs
namespace ProjetFinalWeb2.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

ProjetFinalWeb2/Models/StreamAddViewModel.cs
using stream.api;
namespace ProjetFinalWeb2.Models
{
	public class StreamAddViewModel
	{
		public stream.api.Stream UnStream {  get; set; }
	}
}

ProjetFinalWeb2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetFinalWeb2.Models;
using System.Diagnostics;

namespace ProjetFinalWeb2.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

ProjetFinalWeb2/Controllers/StreamController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjetFinalWeb2.Models;

namespace ProjetFinalWeb2.Controllers
{
	public class StreamController : Controller
	{
		private readonly DefaultDbContext context;

		public StreamController(DefaultDbContext context)
		{
			this.context = context;
		}

		// GET: StreamController
		public IActionResult List()
		{
			// Prepa requete linq => ça ne fait rien
			var query = from item in this.context.Streams
						orderby item.statut
						select item;

			var modelAEnvoyerALaView = query.ToList(); // Traduction, requete linq en requete sql
			var vueAAppeler = "List";
			return View(vueAAppeler, modelAEnvoyerALaView);
		}

		// GET: StreamController/Details/5
		public ActionResult Details(int id)
		{
			return View();
		}

		// GET: StreamController/Create
		public ActionResult Create()
		{
			return View();
		}

		[HttpGet]
		public IActionResult Add()
		{
			return View();
		}

		// POST: StreamController/Add
		[HttpPost]
		public IActionResult Add(StreamAddViewModel item)
		{
			// date = this.Request.Form["date"];
			//string titre = this.Request.Form["titre"];
			//string statut = this.Request.Form["statut"];

			this.context.Streams.Add(item.UnStream);
			//this.context.Personnes.Add(new Personne());

			this.context.SaveChanges();

			return RedirectToAction("List");
		}

		// GET: StreamController/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: StreamController/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}

		// GET: StreamController/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: StreamController/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id, IFormCollection collection)
		{
			try
			{
				return RedirectToAction(nameof(Index));
			}
			catch
			{
				return View();
			}
		}
	}
}

ProjetFinalWeb2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjetFinalWeb2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetFinalWeb2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetFinalWeb2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetFinalWeb2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stream" asp-action="List">Liste des streams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stream" asp-action="Add">Ajouter un stream</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProjetFinalWeb2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjetFinalWeb2/Views/Stream/Add.cshtml
<form asp-action="Add" asp-controller="Stream" method="post">
    <input type="datetime-local" name="UnStream.date" />
    <input type="text" name="UnStream.titre" />
    <select name="UnStream.statut">
        <option value="A venir">A venir</option>
        <option value="En cours">En cours</option>
        <option value="Fini">Fini</option>
    </select>
    <button type="submit">Ajouter</button>
</form>

ProjetFinalWeb2/Views/Stream/List.cshtml
<table class="table">
	<thead>
		<tr>
			<th>
				Date
			</th>
			<th>
				titre
			</th>
			<th>
				statut
			</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var stream in Model)
		{
			<tr>
				<td>@stream.Date</td>
				<td>@stream.titre</td>
				<td>@stream.statut</td>
			</tr>
		}
	</tbody>
</table>